### ISSUE TITLE
about external memory

### ISSUE THREAD

**Issue by andy-sasa** [Malik1998/VSTAM#8]
# don't send the mask
        decoder_mha, weights = self.decoder_mha(((query, context, context), None))
        # use somehow weights to memory saving (in the original paper we use weights
        # of decoder to choose best frames to save)

In your code of video_sparse_transformer_decoder.py, do you use wieghts to choose memory saving??? Or its in other place??

and where did you do that  (in the original paper we use weights of decoder to choose best frames to save)

thanks~~

**Comment by Malik1998** [comment]
Hello,
Thank you for your question!
I tried changing scores here https://github.com/Malik1998/VSTAM/blob/main/iterate_over_dataset.py#L44
And I work with scores in the dataset class here: https://github.com/Malik1998/VSTAM/blob/main/data/dataset.py#L74
But whole pipeline with training + using score isn't implemented yet. it's not very hard, because dataset class have function to change scores and model can return weights of frames

Kind regards,
Malik1998

**Comment by andy-sasa** [comment]
Thank you for reply. 

But I still have some questions about the dataset class in the context of training. The proposal_generator and roi_heads components seem to require something like a gt_instances_list.

So, in my custom dataset, I have formatted it as follows:

[Instances(num_instances=1, image_height=224, image_width=224, fields=[gt_boxes: Boxes(tensor([[24., 26., 85., 90.]], device='cuda:0')), gt_classes: tensor([0], device='cuda:0')])]
Here, Boxes uses coordinates in the format (xmin, ymin, xmax, ymax).

Is this appropriate?

**Comment by Malik1998** [comment]
If I understand you correctly, you are right.
I have mistaken here and made dataset using gt_masks instead of boxes and classes.
Yes, you must use your format, because as far as I understand it's required by detectron2 or by some common losses in detection. 
And also you must add some info that helps you to answer from which video this frame is.
I would be happy if it helps you!)

**Comment by andy-sasa** [comment]
Thank you very much!
You help me a lot, and I train it successfully!
